language: cpp
sudo: true
compiler:
  - clang

os:
  - linux
  - osx
  - windows

install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install visualstudio2017-workload-vctools -y; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sh build/travis-clang.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh build/travis-clang.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then sh build/travis-cl.sh; fi
