set LIB_SRC=%BASE_DIR%lib\filestorage\*.c
set LIB_THIRDPARTY_SRC=%BASE_DIR%src\ext\*.c

set ARCHIVEBLOCKSTORE_SRC=%BASE_DIR%lib\archiveblockstore\*.c

set ATOMICCANCEL_SRC=%BASE_DIR%lib\atomiccancel\*.c

set BLOCKSTORESTORAGE_SRC=%BASE_DIR%lib\blockstorestorage\*.c

set COMPRESSBLOCKSTORE_SRC=%BASE_DIR%lib\compressblockstore\*.c

set CONCURRENTCHUNKWRITE_SRC=%BASE_DIR%lib\concurrentchunkwrite\*.c

set CACHEBLOCKSTORE_SRC=%BASE_DIR%lib\cacheblockstore\*.c

set FILESTORAGE_SRC=%BASE_DIR%lib\*.c

set FSBLOCKSTORE_SRC=%BASE_DIR%lib\fsblockstore\*.c

set HPCDCCHUNKER_SRC=%BASE_DIR%lib\hpcdcchunker\*.c

set LRUBLOCKSTORE_SRC=%BASE_DIR%lib\lrublockstore\*.c

set MEMSTORAGE_SRC=%BASE_DIR%lib\memstorage\*.c

set MEMTRACER_SRC=%BASE_DIR%lib\memtracer\*.c

set MEOWHASH_SRC=%BASE_DIR%lib\meowhash\*.c

set RATELIMITEDPROGRESS_SRC=%BASE_DIR%lib\ratelimitedprogress\*.c

set COMPRESSION_REGISTRY_SRC=%BASE_DIR%lib\compressionregistry\*.c

set HASH_REGISTRY_SRC=%BASE_DIR%lib\hashregistry\*.c

set SHAREBLOCKSTORE_SRC=%BASE_DIR%lib\shareblockstore\*.c

set BIKESHED_SRC=%BASE_DIR%lib\bikeshed\*.c

set BLAKE2_SRC=%BASE_DIR%lib\blake2\*.c
set BLAKE2_THIRDPARTY_SSE=%BASE_DIR%lib\blake2\ext\*.c

set BLAKE3_SRC=%BASE_DIR%lib\blake3\*.c
set BLAKE3_THIRDPARTY_SRC=%BASE_DIR%lib\blake3\ext\blake3.c %BASE_DIR%lib\blake3\ext\blake3_dispatch.c %BASE_DIR%lib\blake3\ext\blake3_portable.c
set BLAKE3_THIRDPARTY_SSE=%BASE_DIR%lib\blake3\ext\blake3_sse2.c %BASE_DIR%lib\blake3\ext\blake3_sse41.c
set BLAKE3_THIRDPARTY_SSE42=
set BLAKE3_THIRDPARTY_AVX2=%BASE_DIR%lib\blake3\ext\blake3_avx2.c
set BLAKE3_THIRDPARTY_AVX512=%BASE_DIR%lib\blake3\ext\blake3_avx512.c
set BLAKE3_THIRDPARTY_NEON=%BASE_DIR%lib\blake3\ext\blake3_neon.c

set LZ4_SRC=%BASE_DIR%lib\lz4\*.c
set LZ4_THIRDPARTY_SRC=%BASE_DIR%lib\lz4\ext\*.c

set BROTLI_SRC=%BASE_DIR%lib\brotli\*.c 
set BROTLI_THIRDPARTY_SRC=%BASE_DIR%lib\brotli\ext\common\*.c %BASE_DIR%lib\brotli\ext\dec\*.c %BASE_DIR%lib\brotli\ext\enc\*.c

set ZSTD_SRC=%BASE_DIR%lib\zstd\*.c
set ZSTD_THIRDPARTY_SRC=%BASE_DIR%lib\zstd\ext\common\*.c %BASE_DIR%lib\zstd\ext\compress\*.c %BASE_DIR%lib\zstd\ext\decompress\*.c
set ZSTD_THIRDPARTY_GCC_SRC=%BASE_DIR%lib\zstd\ext\decompress\*.S

set SRC=%BASE_DIR%src\*.c %LIB_SRC% %ARCHIVEBLOCKSTORE_SRC% %ATOMICCANCEL_SRC% %BLOCKSTORESTORAGE_SRC% %COMPRESSBLOCKSTORE_SRC% %CONCURRENTCHUNKWRITE_SRC% %CACHEBLOCKSTORE_SRC% %SHAREBLOCKSTORE_SRC% %FILESTORAGE_SRC% %FSBLOCKSTORE_SRC% %HPCDCCHUNKER_SRC% %LRUBLOCKSTORE_SRC% %MEMSTORAGE_SRC% %MEMTRACER_SRC% %RATELIMITEDPROGRESS_SRC% %COMPRESSION_REGISTRY_SRC% %HASH_REGISTRY_SRC% %BIKESHED_SRC% %BLAKE2_SRC% %BLAKE3_SRC% %MEOWHASH_SRC% %LZ4_SRC% %BROTLI_SRC% %ZSTD_SRC%
set THIRDPARTY_SRC=%LIB_THIRDPARTY_SRC% %BLAKE3_THIRDPARTY_SRC% %LZ4_THIRDPARTY_SRC% %BROTLI_THIRDPARTY_SRC% %ZSTD_THIRDPARTY_SRC%
set THIRDPARTY_SSE=%BLAKE2_THIRDPARTY_SSE% %BLAKE3_THIRDPARTY_SSE%
set THIRDPARTY_SSE42=%BLAKE3_THIRDPARTY_SSE42%
set THIRDPARTY_SRC_AVX2=%BLAKE3_THIRDPARTY_AVX2%
set THIRDPARTY_SRC_AVX512=%BLAKE3_THIRDPARTY_AVX512%
set THIRDPARTY_SRC_NEON=%BLAKE3_THIRDPARTY_NEON%
set THIRDPARTY_GCC_SRC=%ZSTD_THIRDPARTY_GCC_SRC%
