#!/bin/bash

export CXXFLAGS="$CXXFLAGS -pthread -U_WIN32 -D_GNU_SOURCE -DLONGTAIL_LOG_LEVEL=5 -msse4.1 -maes"
export CXXFLAGS_DEBUG="$CXXFLAGS_DEBUG -D_GNU_SOURCE -DBIKESHED_ASSERTS -DLONGTAIL_LOG_LEVEL=3 -DLONGTAIL_ASSERTS -msse4.1 -maes"
