#!/bin/bash

export CXXFLAGS="$CXXFLAGS -pthread -U_WIN32 -DLONGTAIL_LOG_LEVEL=5 -msse4.1 -maes -DZSTD_DISABLE_ASM"
export CXXFLAGS_DEBUG="$CXXFLAGS_DEBUG -DBIKESHED_ASSERTS -DLONGTAIL_LOG_LEVEL=3 -DLONGTAIL_ASSERTS -msse4.1 -maes -DZSTD_DISABLE_ASM"
