set TARGET=longtail_win32_x64
set TARGET_TYPE=STATICLIB

call ..\default_build_options.bat

set CXXFLAGS=%CXXFLAGS% /DLONGTAIL_EXPORT_SYMBOLS /DZSTDLIB_VISIBILITY="" /DLZ4LIB_VISIBILITY=""
set CXXFLAGS_DEBUG=%CXXFLAGS_DEBUG% /DLONGTAIL_EXPORT_SYMBOLS /DZSTDLIB_VISIBILITY="" /DLZ4LIB_VISIBILITY=""
