name: MacOS-Master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: build test
      run: |
        pushd ./test 
        ../build.sh
        ../build.sh release
        popd
    - name: build cmd
      run: |
        pushd ./cmd
        ../build.sh
        ../build.sh release
        popd
    - name: run tests
      run: |
        pushd ./test
        ../build/test_debug
        ../build/test
        popd
    - name: build dist
      run: |
        mkdir dist
        cp ./build/longtail_debug dist/
        cp ./build/longtail dist/
    - uses: actions/upload-artifact@master
      with:
        name: dist-macos-x64
        path: dist
