name: MacOS-Master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: build test
      run: |
        pushd ./test 
        ../build.sh
        ../build.sh release
        popd
    - name: build cmd
      run: |
        pushd ./cmd
        ../build.sh
        ../build.sh release
        popd
    - name: run tests
      run: |
        pushd ./test
        ../build/test_debug
        ../build/test
        popd
    - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./dist-zip/longtail_debug-macos-x64.zip ./build/longtail_debug
    - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./dist-zip/longtail-macos-x64.zip ./build/longtail
    - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist-zip
