name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build test
      run: |
        cd ./test 
        ../build.bat
        ../build.bat release
        cd ..
    - name: build cmd
      run: |
        cd ./cmd
        ../build.bat
        ../build.bat release
        cd ..
    - name: build shared_lib
      run: |
        cd ./shared_lib
        ../build.bat
        ../build.bat release
        cd ..
    - name: run tests
      run: |
        cd ./test
        ../build/test_debug.exe
        ../build/test.exe
        cd ..
