name: Windows-Master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build test
      run: |
        cd ./test 
        ../build.bat
        ../build.bat release
        cd ..
    - name: build cmd
      run: |
        cd ./cmd
        ../build.bat
        ../build.bat release
        cd ..
    - name: build shared_lib
      run: |
        cd ./shared_lib
        ../build.bat
        ../build.bat release
        cd ..
    - name: run tests
      run: |
        cd ./test
        ../build/test_debug.exe
        ../build/test.exe
        cd ..
    - run: |
        mkdir dist
        copy ./build/longtail_debug.exe dist/
        copy ./build/longtail.exe dist/
        copy ./build/longtail_debug.dll dist/
        copy ./build/longtail.dll dist/
    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist/win-x64
